#application: restu
#version: alpha-001
runtime: php73
service: default

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /web/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2|jpg))
  static_files: content/\1
  upload: content/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2|jpg))

- url: /web/.*
  static_files: content/index.html
  upload: content/index.html
  secure: always
  
# Serve your app through a front controller at index.php or public/index.php.  
- url: .*
  script: auto